### ISSUE TITLE
Components Validator

### ISSUE THREAD

**Issue by ivan-sushko** [PacktPublishing/Building-Forms-with-Vue.js#19]
In Chapter 5 there is the components that crash my npm.

To be prescise, it is validator properties:

   In the book: validator($v) { return hasOwnProperty("$model" )};

   I replaced it with: validator($v) { return hasOwnProperty.call($v, "$model" )}; and it runs well for me.

**Comment by sonam-packt** [comment]
@ivan-sushko  Thank you for the suggestion
